[project]
name = "pico_chat"
version = "0.7.0"
description = "Local AI assistant in the command line"
requires-python = ">= 3.10"
authors = [{name = "Joackim Orciere", email = "joackim.orciere@proton.me"}]
dependencies = [
    "openai",
    "toml",
    
    # Pinned dependencies for stability and avoiding supply-chain issues
    # > Theses packages do not have dependencies of their own so we can safely pin them 
    "pathspec == 1.0.4", # For .gitignore parsing
    "wcwidth == 0.6.0",  # For accurate character width calculation in the terminal
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {}}

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pico_chat = { path = ".", editable = true, extras = ["git"] }

[tool.pixi.tasks]
tests = "pytest tests/"
minichat = "python minichat.py"
app = "python pico_chat/main.py"

[tool.pixi.dependencies]
ipykernel = "*"
pytest = "*"
# pytest-html = "*"
# matplotlib-base = "*"
pytest-xdist = "*"
# pillow = "*"
openai = "*"
toml = "*"
wcwidth = "==0.6.0"
